server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    # CORRECTION IS HERE
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate



  h2:
    console:
      enabled: false

  application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY} # A nossa chave secreta virá do ambiente
        expiration: 86400000