server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:encurtalink}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibertane.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: false

  application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY} # A nossa chave secreta virá do ambiente
        expiration: 86400000